### ISSUE TITLE
ENGINE-REST-HTTP500 org.camunda.connect.ConnectorRequestException: HTCL-02007 Unable to execute HTTP request

### ISSUE THREAD

**Issue by jlema0590** [camunda-community-hub/camunda-helm#22]
Camunda with docker tag tomcat 

![image](https://user-images.githubusercontent.com/25331403/140298029-9c4699a9-244d-4460-af46-02f9971e13b3.png)

Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

How to solve this problem?

**Comment by aabouzaid** [comment]
Hi @jlema0590 please add more details about your setup and how to reproduce this issue.

**Comment by aabouzaid** [comment]
Closing the issue since it's not reproducible and no updates over the last 30 days.
