### ISSUE TITLE
Migrate extension to the Camunda Community Hub

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-helm#3]
Hello! I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/camunda-community-hub/community)?

We'd love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. If you are no longer able to maintain this extension, if it is migrated to the Hub I would be more than happy to add a [lifecycle badge](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to it indicating that the project is in need of a new maintainer.

I'm also more than happy to schedule a call and talk over this in more detail if that would be preferable to you, for whenever best suits your schedule over the next few weeks.

Thank you so much for your time. I look forward to hearing from you.

**Comment by celanthe** [comment]
Hi @aabouzaid! As this has been migrated to the community Hub, I'll go ahead and close this issue! Thanks so much! :)

**Comment by aabouzaid** [comment]
@celanthe Thanks Rin :+1:
