### ISSUE TITLE
HTTPs port not declared in Camunda Service when run in production mode

### ISSUE THREAD

**Issue by palex351** [camunda-community-hub/camunda-helm#39]
Camunda started in production mode with the configuration:
> camunda-bpm-platform:
>   image:
>     command: ['./camunda.sh']
>     args: ['--production']

K8s services only declares http port

**Comment by aabouzaid** [comment]
It's now possible to customize the port config in [v1.5.0](https://github.com/camunda-community-hub/camunda-helm/releases/tag/camunda-bpm-platform-1.5.0).
