### ISSUE TITLE
Add additional containers

### ISSUE THREAD

**Issue by op-euga** [camunda-community-hub/camunda-helm#45]
We use camunda with our self created manifest files and want to switch to the helm chart. As we use google cloud and want to connect to our DBs by using the cloudsql proxy. it would be nice, if you can add the possibility to add additional (sidecar) containers to the deployment.

**Comment by thecampagnards** [comment]
Hello done in #47 :)

**Comment by aabouzaid** [comment]
The feature was added by @thecampagnards and released in [v1.6.0](https://github.com/camunda-community-hub/camunda-helm/releases/tag/camunda-bpm-platform-1.6.0).
