### ISSUE TITLE
Refactor repo to avoid confusion with Camunda Platform 8

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/camunda-helm#46]
Can this repo be refactored to avoid clashing with Camunda Platform 8 Helm charts? It's creating a lot of confusion (ie helm.camunda.cloud vs helm.camunda.io) as well as instructions (helm repo add camunda......) It should be more obvious you're working with Camunda Platform 7 (helm.camunda.bpm or something along those lines) and (helm repo add camunda-bpm...)

**Comment by aabouzaid** [comment]
Thanks @superbeagle for your suggestion, totally makes sense.

I've mentioned Camunda Platform 7 clearly in the chart and docs as well as a link for the official [Camunda Platform 8 Helm repo](https://github.com/camunda/camunda-platform-helm).
Also, I've used v7 as a base version for the chart.

It has been released as: [camunda-bpm-platform-7.6.0](https://github.com/camunda-community-hub/camunda-helm/releases/tag/camunda-bpm-platform-7.6.0)
