### ISSUE TITLE
[FIX][PR] Postgres connection failed

### ISSUE THREAD

**Issue by xoojulian** [camunda-community-hub/camunda-helm#9]
Installed with Postgres configuration and initialized successfully.
During operation, the database connection raised the following errors:
`PSQLException: Cannot commit when autoCommit is enabled`
According to googled solutions, one is working perfectly adding the following environment:
`DB_VALIDATE_ON_BORROW` = `true`
#8 PR submitted

**Comment by aabouzaid** [comment]
Fixed by PR no. #13
